[project]
name = "yokai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fuzzywuzzy>=0.18.0",
    "prompt-toolkit>=3.0.51",
    "python-levenshtein>=0.27.1",
]
