name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Update system and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm wget tar git clang

    - name: Download and setup Zig 0.14.0
      run: |
        wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
        tar -xf zig-linux-x86_64-0.14.0.tar.xz
        mv zig-linux-x86_64-0.14.0 zig
        echo "$PWD/zig" >> $GITHUB_PATH

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check formatting
      run: ./zig/zig build format -Dcheck_format=true

    - name: Build project
      run: ./zig/zig build
